import { useEffect, useState, useRef } from "react";
import { useParams, Link, useNavigate } from "react-router-dom";
import { ArrowLeft, Play, Sparkles, Copy, Check, Loader2, RefreshCw } from "lucide-react";
import { useUser } from "../services/UserContext";
import { getNewsById, getAIAnalysisByNewsId } from "../services/newsApi";
import Header from "../components/Header";
import TickerTape from "../components/TickerTape";

const AIAnalysisPage = () => {
  const { id } = useParams();
  const navigate = useNavigate();
  const { user } = useUser();

  const [newsItem, setNewsItem] = useState(null);
  const [loadingNews, setLoadingNews] = useState(true);
  const [newsError, setNewsError] = useState(null);

  // AI Analysis States
  const [analysisRaw, setAnalysisRaw] = useState(null);
  const [loadingAnalysis, setLoadingAnalysis] = useState(false);
  const [analysisError, setAnalysisError] = useState(null);

  // Chat/Typing States
  const [chatStage, setChatStage] = useState("idle"); // "idle", "sending", "analyzing", "typing", "complete"
  const [displayedText, setDisplayedText] = useState("");
  const [isCopied, setIsCopied] = useState(false);
  
  const typingTimerRef = useRef(null);
  const chatEndRef = useRef(null);
  const chatContainerRef = useRef(null);

  // 1. Fetch News Article Details
  useEffect(() => {
    const fetchNews = async () => {
      try {
        setLoadingNews(true);
        setNewsError(null);
        const data = await getNewsById(id);
        if (data && data.news) {
          setNewsItem(data.news);
        } else {
          setNewsError("Article not found");
        }
      } catch (err) {
        console.error(err);
        setNewsError("Failed to retrieve article details");
      } finally {
        setLoadingNews(false);
      }
    };
    fetchNews();
  }, [id]);

  // Redirect if user is not logged in (locked feature protection)
  useEffect(() => {
    if (!loadingNews && !user) {
      navigate(`/news/${id}`);
    }
  }, [user, loadingNews, navigate, id]);

  // Clean up typing animation on unmount
  useEffect(() => {
    return () => {
      if (typingTimerRef.current) clearInterval(typingTimerRef.current);
    };
  }, []);

  // Auto-scroll chat window when typing, but only if the user is already near the bottom
  useEffect(() => {
    if ((chatStage === "typing" || chatStage === "sending") && chatContainerRef.current) {
      const container = chatContainerRef.current;
      const threshold = 35; // small threshold: a minor scroll up will instantly pause auto-scroll
      const isNearBottom = container.scrollHeight - container.scrollTop - container.clientHeight <= threshold;
      
      if (isNearBottom) {
        // Use instant scroll (scrollTop mutation) to prevent smooth scroll animation queues from fighting the user
        container.scrollTop = container.scrollHeight;
      }
    }
  }, [displayedText, chatStage]);

  // Assemble JSON fields into a beautiful, structured markdown document
  const buildMarkdownReport = (news, analysis) => {
    const cleanTitle = news.title || "Market Analysis";

    let md = `### 📊 AI Financial Analysis: ${cleanTitle}
*Generated by MarketMind Intelligence*

**1. Event Explanation**
${analysis.newsExplanation || "Analysis not available."}

**2. Market & Sector Impact**
${analysis.marketImpact || "Analysis not available."}

**3. Core Sentiment & Outlook**
• **Outlook:** ${analysis.outlook || "N/A"}
• **Sentiment:** ${analysis.sentiment || "N/A"}
• **Confidence Score:** ${analysis.confidenceScore || 0}%

**4. Fundamental Valuation**
• **Valuation:** ${analysis.fundamentalAnalysis?.valuation || "Data Not Available"}
• **Profitability:** ${analysis.fundamentalAnalysis?.profitability || "Data Not Available"}
• **Growth:** ${analysis.fundamentalAnalysis?.growth || "Data Not Available"}
• **Financial Health:** ${analysis.fundamentalAnalysis?.financialHealth || "Data Not Available"}
• **Overall Quality:** ${analysis.fundamentalAnalysis?.overallInterpretation || "Data Not Available"}

**5. Investor Strategic Insights**
• **For Existing Shareholders:** ${analysis.investorInsight?.existingInvestors || "Analysis not available."}
• **For Prospective Buyers:** ${analysis.investorInsight?.newInvestors || "Analysis not available."}`;

    if (analysis.risks && analysis.risks.length > 0) {
      md += `\n\n**6. Key Risks Identified**\n${analysis.risks.map((r) => `• ${r}`).join("\n")}`;
    }

    return md;
  };

  // Trigger the AI request sequence
  const handleInitiateAnalysis = async () => {
    setChatStage("sending");
    setAnalysisError(null);

    // Simulate sending message delay
    await new Promise((resolve) => setTimeout(resolve, 800));
    setChatStage("analyzing");

    try {
      // Fetch analysis from backend
      const data = await getAIAnalysisByNewsId(id);
      
      if (data && data.success) {
        setAnalysisRaw(data.analysis);
        const markdown = buildMarkdownReport(newsItem, data.analysis);
        
        // Transition to typing
        setChatStage("typing");
        startTypingSimulation(markdown);
      } else {
        throw new Error(data.message || "Failed to generate analysis");
      }
    } catch (err) {
      console.error(err);
      const errMsg = err.response?.data?.message || "AI Analysis is currently unavailable due to rate limits. Please try again later.";
      setAnalysisError(errMsg);
      setChatStage("idle");
    }
  };

  // Simulate typing effect (typewriter style)
  const startTypingSimulation = (fullText) => {
    if (!fullText) return;
    if (typingTimerRef.current) clearInterval(typingTimerRef.current);
    
    const chars = [...fullText];
    let currentIndex = 0;
    // Blazing-fast high-performance streaming speed (prints 3 characters every 8 milliseconds)
    const typingSpeed = 8;
    const charsPerTick = 3;
    
    typingTimerRef.current = setInterval(() => {
      if (currentIndex >= chars.length) {
        clearInterval(typingTimerRef.current);
        setChatStage("complete");
        return;
      }
      
      const nextChunk = chars.slice(currentIndex, currentIndex + charsPerTick).join("");
      currentIndex += charsPerTick;
      
      setDisplayedText((prev) => prev + nextChunk);
      
      if (currentIndex >= chars.length) {
        clearInterval(typingTimerRef.current);
        setChatStage("complete");
      }
    }, typingSpeed);
  };

  // Copy markdown report to clipboard
  const handleCopyClipboard = () => {
    if (newsItem && analysisRaw) {
      const markdown = buildMarkdownReport(newsItem, analysisRaw);
      navigator.clipboard.writeText(markdown);
      setIsCopied(true);
      setTimeout(() => setIsCopied(false), 2000);
    }
  };

  // Custom parser to transform formatted markdown lines into gorgeous styled HTML components
  const renderFormattedAIResponse = (text) => {
    return text.split("\n").map((line, idx) => {
      // H3 Headers
      if (line.startsWith("###")) {
        return (
          <h3 key={idx} className="font-serif text-xl sm:text-2xl text-text-0 mt-6 mb-3 border-b border-border-custom pb-1 transition-colors font-semibold">
            {line.replace("###", "").trim()}
          </h3>
        );
      }
      
      // Bold Section Titles
      if (line.startsWith("**") && line.endsWith("**")) {
        return (
          <h4 key={idx} className="font-sans font-bold text-xs text-text-0 mt-5 mb-2 uppercase tracking-wider transition-colors font-bold">
            {line.replace(/\*\*/g, "").trim()}
          </h4>
        );
      }

      // Bullet points & fundamentals
      if (line.startsWith("•") || line.startsWith("-")) {
        const cleanedLine = line.replace(/^[•-]\s*/, "");
        // Match bold keys in bullet points e.g. "• **Outlook:** Positive"
        const boldRegex = /\*\*(.*?)\*\*/g;
        const parts = [];
        let lastIndex = 0;
        let match;
        
        while ((match = boldRegex.exec(cleanedLine)) !== null) {
          if (match.index > lastIndex) {
            parts.push(cleanedLine.substring(lastIndex, match.index));
          }
          parts.push(<strong key={match.index} className="font-semibold text-text-0">{match[1]}</strong>);
          lastIndex = boldRegex.lastIndex;
        }
        
        if (lastIndex < cleanedLine.length) {
          parts.push(cleanedLine.substring(lastIndex));
        }

        return (
          <li key={idx} className="ml-4 list-disc list-outside text-text-1 mb-2 leading-relaxed pl-1 transition-colors text-xs sm:text-sm">
            {parts.length > 0 ? parts : cleanedLine}
          </li>
        );
      }

      // Standard paragraphs with potential inline bold text
      if (line.includes("**")) {
        const boldRegex = /\*\*(.*?)\*\*/g;
        const parts = [];
        let lastIndex = 0;
        let match;
        
        while ((match = boldRegex.exec(line)) !== null) {
          if (match.index > lastIndex) {
            parts.push(line.substring(lastIndex, match.index));
          }
          parts.push(<strong key={match.index} className="font-semibold text-text-0">{match[1]}</strong>);
          lastIndex = boldRegex.lastIndex;
        }
        
        if (lastIndex < line.length) {
          parts.push(line.substring(lastIndex));
        }

        return (
          <p key={idx} className="text-text-1 mb-3 leading-relaxed transition-colors text-xs sm:text-sm">
            {parts}
          </p>
        );
      }

      // Spacing for empty lines
      if (line.trim() === "") {
        return <div key={idx} className="h-3" />;
      }

      // Standard text line
      return (
        <p key={idx} className="text-text-1 mb-3 leading-relaxed transition-colors text-xs sm:text-sm">
          {line}
        </p>
      );
    });
  };

  if (loadingNews) {
    return (
      <div className="min-h-screen bg-bg-0 text-text-0 transition-colors duration-300">
        <Header />
        <TickerTape />
        <div className="flex min-h-[65vh] flex-col items-center justify-center gap-3">
          <Loader2 className="animate-spin text-bull" size={36} />
          <p className="font-mono text-sm text-text-2 tracking-wider">Accessing Secure Terminal...</p>
        </div>
      </div>
    );
  }

  if (newsError || !newsItem) {
    return (
      <div className="min-h-screen bg-bg-0 text-text-0 transition-colors duration-300">
        <Header />
        <TickerTape />
        <div className="mx-auto max-w-xl px-6 py-20 text-center">
          <h2 className="font-serif text-3xl mb-4 text-text-0">Access Denied</h2>
          <p className="text-sm text-text-2 mb-8">{newsError || "Unable to locate news article."}</p>
          <Link
            to="/"
            className="inline-flex items-center gap-2 rounded-xl border border-border-strong bg-bg-1 hover:bg-border-custom/50 px-5 py-3 transition-colors text-sm font-medium shadow-sm cursor-news"
          >
            <ArrowLeft size={16} />
            Return to Terminal
          </Link>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-bg-0 text-text-0 transition-colors duration-300">
      <Header />
      <TickerTape />

      <main className="mx-auto max-w-4xl px-4 py-8 sm:px-6 lg:py-12">
        
        {/* BACK LINK */}
        <div className="mb-6">
          <Link
            to={`/news/${id}`}
            className="inline-flex items-center gap-2 font-mono text-[11px] uppercase tracking-wider text-text-2 hover:text-bull transition-colors"
          >
            <ArrowLeft size={12} />
            Back to Article
          </Link>
        </div>

        {/* TERMINAL HEADER SECTION */}
        <div className="mb-4 flex flex-col gap-2">
          <h1 className="font-serif text-2xl sm:text-3xl text-text-0 transition-colors truncate">
            Research Terminal: {newsItem.title}
          </h1>
          <p className="text-xs text-text-2 font-sans transition-colors truncate">
            Subject: {newsItem.source} / Published {new Date(newsItem.published_at).toLocaleDateString()}
          </p>
        </div>

        {/* MACOS WINDOW TERMINAL CARDS */}
        <div className="relative overflow-hidden rounded-2xl border border-border-strong bg-bg-1 shadow-lg flex flex-col transition-colors duration-300 min-h-[580px]">
          
          {/* TERMINAL TITLE BAR */}
          <div className="flex items-center justify-between bg-bg-2 border-b border-border-strong px-4 py-3 select-none transition-colors duration-300">
            {/* macOS control dots */}
            <div className="flex items-center gap-1.5">
              <span className="h-3 w-3 rounded-full bg-[#ff5f56] border border-[#e0443e]" />
              <span className="h-3 w-3 rounded-full bg-[#ffbd2e] border border-[#dea123]" />
              <span className="h-3 w-3 rounded-full bg-[#27c93f] border border-[#1aab29]" />
            </div>
            
            {/* Window title */}
            <div className="absolute left-1/2 -translate-x-1/2 font-mono text-[10px] text-text-2 tracking-wider uppercase hidden sm:block">
              MarketMind AI Terminal v3.1
            </div>

            {/* Live Indicator */}
            <div className="flex items-center gap-1.5">
              <span className={`h-2 w-2 rounded-full ${chatStage === "typing" || chatStage === "analyzing" ? "bg-bull animate-pulse" : "bg-text-3"}`} />
              <span className="font-mono text-[9px] uppercase tracking-wider text-text-2">
                {chatStage === "typing" ? "Streaming" : chatStage === "analyzing" ? "Analyzing" : "Online"}
              </span>
            </div>
          </div>

          {/* CHAT DISPLAY CONTAINER */}
          <div
            ref={chatContainerRef}
            id="chat-history"
            className="flex-1 p-5 overflow-y-auto font-sans flex flex-col gap-6 max-h-[480px] min-h-[420px]"
          >
            
            {/* MESSAGE 1: AI GREETING (STAYS ACTIVE) */}
            <div className="flex items-start gap-3 max-w-[85%]">
              <div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-bull/10 text-bull border border-bull/20 font-mono text-sm font-bold shadow-sm">
                AI
              </div>
              <div className="flex flex-col gap-1 rounded-2xl bg-bg-2 border border-border-custom px-4 py-3 text-xs sm:text-sm text-text-1 shadow-sm leading-relaxed transition-colors">
                <p>
                  Welcome to the AI Research Terminal. I have compiled the fundamental financial metrics and parsed the news narrative. 
                </p>
                <p className="mt-2">
                  Initiate the analysis below, and I will stream the deep research breakdown, valuation models, sentiment analysis, and risk evaluation for you.
                </p>
              </div>
            </div>

            {/* MESSAGE 2: USER REQUEST (TRIGGERS WHEN INITIATED) */}
            {(chatStage !== "idle") && (
              <div className="flex items-start gap-3 max-w-[85%] self-end flex-row-reverse">
                <div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-black/5 dark:bg-white/5 text-text-1 border border-border-custom font-mono text-sm font-bold shadow-sm">
                  U
                </div>
                <div className="flex flex-col gap-1 rounded-2xl bg-bg-0 border border-border-custom px-4 py-3 text-xs sm:text-sm text-text-1 shadow-sm leading-relaxed transition-colors">
                  Initiate deep financial analysis and risk evaluation report.
                </div>
              </div>
            )}

            {/* MESSAGE 3: AI STREAMING RESPONSE */}
            {(chatStage === "analyzing" || chatStage === "typing" || chatStage === "complete") && (
              <div className="flex items-start gap-3 w-full">
                <div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-bull/10 text-bull border border-bull/20 font-mono text-sm font-bold shadow-sm">
                  AI
                </div>
                <div className="flex-1 rounded-2xl bg-bg-2 border border-border-custom px-5 py-4 text-text-1 shadow-sm transition-colors relative min-h-[100px]">
                  
                  {/* Server loading state */}
                  {chatStage === "analyzing" && (
                    <div className="flex items-center gap-2.5 text-xs sm:text-sm text-text-2 font-mono py-2">
                      <Loader2 className="animate-spin text-bull" size={16} />
                      Analyzing market structures and stock ratios...
                    </div>
                  )}

                  {/* Typewriter Output */}
                  {(chatStage === "typing" || chatStage === "complete") && (
                    <div className="prose dark:prose-invert max-w-none">
                      {renderFormattedAIResponse(displayedText)}
                      
                      {/* Blinking terminal cursor */}
                      {chatStage === "typing" && (
                        <span className="inline-block h-4 w-2 bg-bull ml-0.5 animate-pulse rounded-sm align-middle" />
                      )}
                    </div>
                  )}
                </div>
              </div>
            )}
            
            {/* Auto Scroll Anchor */}
            <div ref={chatEndRef} />
          </div>

          {/* CONTROL / INPUT BAR */}
          <div className="bg-bg-2 border-t border-border-strong p-4 flex flex-col sm:flex-row items-center justify-between gap-4 transition-colors duration-300 select-none">
            
            {/* Status Information */}
            <div className="text-[10px] sm:text-xs font-mono text-text-2 transition-colors flex-1 text-left">
              {chatStage === "idle" && "Ready to analyze."}
              {chatStage === "sending" && "Sending instruction..."}
              {chatStage === "analyzing" && "Connecting to server..."}
              {chatStage === "typing" && "Streaming live report..."}
              {chatStage === "complete" && "Analysis complete."}
            </div>

            {/* Interactive Actions */}
            <div className="flex items-center gap-2.5 w-full sm:w-auto justify-end">
              
              {/* ERROR ALERT NOTICE */}
              {analysisError && (
                <span className="text-xs text-bear mr-2 font-mono truncate max-w-[200px] sm:max-w-xs transition-colors">
                  Error: API Quota Exceeded
                </span>
              )}

              {/* ACTION BUTTONS */}
              {chatStage === "idle" && (
                <button
                  onClick={handleInitiateAnalysis}
                  className="w-full sm:w-auto inline-flex items-center justify-center gap-2 rounded-xl bg-bull hover:bg-bull/90 text-white px-5 py-3 transition-colors text-xs font-bold shadow-md hover:shadow-lg cursor-news active:scale-[0.98]"
                >
                  <Sparkles size={14} />
                  Initiate AI Analysis
                </button>
              )}

              {chatStage === "analyzing" && (
                <button
                  disabled
                  className="w-full sm:w-auto inline-flex items-center justify-center gap-2 rounded-xl bg-border-custom text-text-2 px-5 py-3 text-xs font-bold transition-colors shadow-sm"
                >
                  <Loader2 className="animate-spin text-text-2" size={14} />
                  Analyzing Data...
                </button>
              )}



              {chatStage === "complete" && (
                <div className="flex items-center gap-2 w-full sm:w-auto justify-end">
                  <button
                    onClick={handleCopyClipboard}
                    className="flex-1 sm:flex-initial inline-flex items-center justify-center gap-2 rounded-xl border border-border-strong bg-bg-1 hover:bg-border-custom/50 px-5 py-3 transition-colors text-xs font-bold shadow-sm cursor-news text-text-1 active:scale-[0.98]"
                  >
                    {isCopied ? (
                      <>
                        <Check size={14} className="text-[#0a8c5b]" />
                        Report Copied
                      </>
                    ) : (
                      <>
                        <Copy size={14} />
                        Copy Report
                      </>
                    )}
                  </button>

                  <button
                    onClick={() => navigate(`/news/${id}`)}
                    className="flex-1 sm:flex-initial inline-flex items-center justify-center gap-2 rounded-xl bg-bull hover:bg-bull/90 text-white px-5 py-3 transition-colors text-xs font-bold shadow-md hover:shadow-lg cursor-news active:scale-[0.98]"
                  >
                    Return to Article
                  </button>
                </div>
              )}

              {/* RETRY BUTTON ON FAILURE */}
              {analysisError && chatStage === "idle" && (
                <button
                  onClick={handleInitiateAnalysis}
                  className="w-full sm:w-auto inline-flex items-center justify-center gap-2 rounded-xl border border-bear/20 bg-bear/5 hover:bg-bear/10 text-bear px-4 py-3 transition-colors text-xs font-bold cursor-news active:scale-[0.98]"
                >
                  <RefreshCw size={12} />
                  Retry Request
                </button>
              )}

            </div>
          </div>
        </div>
      </main>
    </div>
  );
};

export default AIAnalysisPage;
